# Generated by Django 4.1.6 on 2023-07-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author_first_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Imię autora'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_last_name',
            field=models.CharField(default='placeholder', max_length=500, verbose_name='Nazwisko autora'),
            preserve_default=False,
        ),
    ]
