# Generated by Django 4.1.6 on 2023-07-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_author_book_author_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_first_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_last_name',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nazwisko i imię autora'),
        ),
    ]
