# Generated by Django 4.1.6 on 2023-07-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data dodania'),
        ),
    ]
