# Generated by Django 4.2.11 on 2025-06-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=500,
                null=True,
                verbose_name="Nazwisko i imię autora/ki",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="date_added",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Data dodania"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="review",
            field=models.URLField(
                blank=True, max_length=1000, null=True, verbose_name="Recenzja"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(db_index=True, max_length=500, verbose_name="Tytuł"),
        ),
        migrations.AlterField(
            model_name="bookgenre",
            name="name",
            field=models.CharField(
                db_index=True, max_length=500, verbose_name="Gatunek"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["title", "author"], name="books_book_title_b7b426_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["-date_added"], name="books_book_date_ad_fc690a_idx"
            ),
        ),
    ]
